observable: '3x2pt'
#Observables 
#     'WL' -> shear-shear
#     'GC' -> photo-clustering
#     '3x2pt' -> 3x2pt: shear-shear, photo-clustering, galaxy-galaxy lensing


likelihood: 'determinants'
#Likelihood
#      'determinants' -> using determinants and summing over all integer ell-values
#      'binned' -> using covariance and differences between data vectors


specs:
  #Scale cuts
  #'const_lmax' -> same lmax in all z-bins
  #'lmax' -> vary lmax in each z-bin
  #'kmax' -> vary kmax in each z-bin, which technically equals to the 'lmax'-option via lmax=kmax rcom(z_mod)/(1+z_mod)
  #           with z_mod corresponding to a peak of the shear and photo-GC kernels 
  scale_cuts:
    type: 'const_lmax'
    max_WL: #[4900]
            [2800, 2800, 2800, 2800, 2800, 
                   3000, 3000, 3000, 3000, 
                         3000, 3000, 3000, 
                               3000, 3000,
                                     3000] #always a list, same length as nbin*(nbin+1)/2 or just 1 for const_lmax
            #[5., 3., 3., 2., 2.]
    max_GC: #[1000]
            #[478, 478, 478, 478, 478, 
            #      617, 617, 617, 617, 
            #           716, 716, 716, 
            #                780, 780,
            #                     818] #always a list, same length as nbin*(nbin+1)/2 or just 1 for const_lmax
            [68, 68, 68, 68, 68, 
                 88, 88, 88, 88, 
                 102, 102, 102, 
                 111, 111,
                 116] 
            #[204, 204, 204, 204, 204, 
            #      264, 264, 264, 264, 
            #           306, 306, 306, 
            #                334, 334,
            #                     350] 
            #[0.7, 0.7, 0.7, 0.7, 0.7]
    cosmo: # for transformation from k_eff to ell
      'Omega_m': 0.31
      'w0': -1.
      'wa': 0.

  #Survey info
  #     Euclid: Euclid_Y1, Euclid_5bins or Euclid_10bins
  #     LSST: LSST_Y1 or LSST_Y10 
  #----- not implemented yet:  
  #     Custom: analytical n(z) or from file
  survey_info: 'LSST_Y1' #'Euclid_Y1' #'Euclid_5bins'
  custom_survey_path: 


data:
  add_noise: False
  type: 0
  #Types:
  #     0 -> compute for a given model and likelihood
  #----- not implemented yet:  
  #     1 -> read from a file
  data_file: 

  nl_model: 0
  #bacco_option: 'z_extrap_hmcode'
  #Nonlinear power spectrum
  #     0 -> HMcode
  #     1 -> bacco
  #     2 -> nDGP
  #     3 -> gLEMURS
  #     4 -> μ-Σ (Σ is not properly implemented in Cls yet)
  #     5 -> Dark Scattering (Interacting Dark Energy)
  bias_model: 2
  # Photometric galaxy bias model (redshift dependence)
  #     0 -> constant linear bias within bins
  #     1 -> (b1, b2) constant within bins
  #     2 -> heft
  ia_model: 0
  # Intrinsic alignment model
  #     0 -> zNLA
  #     1 -> TATT
  baryon_model: 0
  # Baryonic flag
  #     0 -> no baryons
  #     1 -> Tagn HMcode
  #     2 -> bcemu
  #     3 -> bacco
  photoz_err_model: 0
  # Photo-z error on n(z) model
  #     0 -> no photo-z error
  #     1 -> additive mode, n(z') = n(z + dz)
  #     2 -> multiplicative mode, n(z') = n(z(1 + dz))
  params: ./params_data.yaml

theory:
  add_noise: False
  nl_model: 0
  #bacco_option: 'z_extrap_hmcode'
  #Nonlinear power spectrum
  #     0 -> HMcode
  #     1 -> bacco
  #     2 -> nDGP
  #     3 -> gLEMURS
  #     4 -> μ-Σ (Σ is not properly implemented in Cls yet)
  #     5 -> Dark Scattering (Interacting Dark Energy)
  bias_model: 0
  # Photometric galaxy bias model (redshift dependence)
  #     0 -> linear interpolation
  #     1 -> constant within bins
  #     2 -> heft
  ia_model: 0
  # Intrinsic alignment model
  #     0 -> zNLA
  #     1 -> TATT
  baryon_model: 0
  # Baryonic flag
  #     0 -> no baryons
  #     1 -> Tagn HMcode
  #     2 -> bcemu
  #     3 -> bacco
  photoz_err_model: 0
  # Photo-z error on n(z) model
  #     0 -> no photo-z error
  #     1 -> additive mode, n(z') = n(z + dz)
  #     2 -> multiplicative mode, n(z') = n(z(1 + dz))
  params: ./params_model_hmcode.yaml  #./params_bacco_b1_test.yaml 

output: 
  chain_name: lsst_y1_3x2pt_hmcode_test
sampler: 
  mcmc:
    verbose: True
    n_eff: 10000
    n_live: 1000
    pool: 20
    resume: False
    hdf5_name: lsst_y1_3x2pt_hmcode_test
    
