observable: 'WL'
#Observables 
#     'WL' -> shear-shear
#     'GC' -> photo-clustering
#     '3x2pt' -> 3x2pt: shear-shear, photo-clustering, galaxy-galaxy lensing


likelihood: 'binned'
#Likelihood
#      'determinants' -> using determinants and summing over all integer ell-values
#      'binned' -> using covariance and differences between data vectors


specs:
  #Scale cuts
  #'const_lmax' -> same lmax in all z-bins
  #'lmax' -> vary lmax in each z-bin
  #'kmax' -> vary kmax in each z-bin, which technically equals to the 'lmax'-option via lmax=kmax rcom(z_mod)/(1+z_mod)
  #           with z_mod corresponding to a peak of the shear and photo-GC kernels 
  scale_cuts:
    type: 'kmax'
    max_WL: #[2000, 2000, 2000, 2000, 2000, 
            #       2000, 2000, 2000, 2000, 
            #             2000, 2000, 2000, 
            #                   2000, 2000,
            #                         1000] #always a list, same length as nbin*(nbin+1)/2 or just 1 for const_lmax
            [5., 3., 3., 2., 2.]
    max_GC: #[600, 600, 600, 600, 600, 
            #      600, 600, 600, 600, 
            #           600, 600, 600, 
            #                900, 900,
            #                     900] #always a list, same length as nbin*(nbin+1)/2 or just 1 for const_lmax
            [0.7, 0.7, 0.7, 0.7, 0.7]
    cosmo: # for transformation from k_eff to ell
      'Omega_m': 0.31
      'w0': -1.
      'wa': 0.

  #Survey info
  #     Euclid: Euclid_Y1, Euclid_5bins or Euclid_10bins
  #     LSST: LSST_Y1 or LSST_Y10 
  #----- not implemented yet:  
  #     Custom: analytical n(z) or from file
  survey_info: 'LSST_Y1' #'Euclid_Y1' #'Euclid_5bins'
  custom_survey_path: 


data:
  type: 0
  #Types:
  #     0 -> compute for a given model and likelihood
  #----- not implemented yet:  
  #     1 -> read from a file
  data_file: 

  nl_model: 1
  #bacco_option: 'linear'
  #Nonlinear power spectrum
  #     0 -> HMcode
  #     1 -> bacco
  #     2 -> nDGP
  #     3 -> gLEMURS
  #     4 -> μ-Σ 
  #     5 -> Dark Scattering (Interacting Dark Energy)
  bias_model: 2
  # Photometric galaxy bias model (redshift dependence)
  #     0 -> constant linear bias within bins
  #     1 -> (b1, b2) constant within bins
  #     2 -> heft
  ia_model: 0
  # Intrinsic alignment model
  #     0 -> zNLA
  #     1 -> TATT
  baryon_model: 0
  # Baryonic flag
  #     0 -> no baryons
  #     1 -> Tagn HMcode
  #     2 -> bcemu
  #     3 -> bacco
  photoz_err_model: 0
  # Photo-z error on n(z) model
  #     0 -> no photo-z error
  #     1 -> additive mode, n(z') = n(z + dz)
  #     2 -> multiplicative mode, n(z') = n(z(1 + dz))
  params: ./params_data.yaml

theory:
  nl_model: 1
  #bacco_option: 'linear'
  #Nonlinear power spectrum
  #     0 -> HMcode
  #     1 -> bacco
  #     2 -> nDGP
  #     3 -> gLEMURS
  #     4 -> μ-Σ 
  #     5 -> Dark Scattering (Interacting Dark Energy)
  bias_model: 2
  # Photometric galaxy bias model (redshift dependence)
  #     0 -> linear interpolation
  #     1 -> constant within bins
  #     2 -> heft
  ia_model: 0
  # Intrinsic alignment model
  #     0 -> zNLA
  #     1 -> TATT
  baryon_model: 0
  # Baryonic flag
  #     0 -> no baryons
  #     1 -> Tagn HMcode
  #     2 -> bcemu
  #     3 -> bacco
  photoz_err_model: 2
  # Photo-z error on n(z) model
  #     0 -> no photo-z error
  #     1 -> additive mode, n(z') = n(z + dz)
  #     2 -> multiplicative mode, n(z') = n(z(1 + dz))
  params: ./params_bacco_test.yaml

output: 
  chain_name: params_debug_bacco
sampler: 
  mcmc:
    verbose: True
    n_eff: 10000
    n_live: 1000
    pool: 20
    resume: False
    hdf5_name: 'params_debug_bacco'

    
