observable: 'wl'
#Observables
#     'WL' -> shear-shear
#     'GC' -> photo-clustering
#     '3x2pt' -> 3x2pt: shear-shear, photo-clustering, galaxy-galaxy lensing
#----- not implemented yet:
#     'XC' -> cross-correlation, galaxy-galaxy lensing
#     '2x2pt' -> 2x2pt: photo-clustering, galaxy-galaxy lensing
specs:
  #Scale cuts
  #'const_lmax' -> same lmax in all z-bins
  #'lmax' -> vary lmax in each z-bin
  #'kmax' -> vary kmax in each z-bin, which technically equals to the 'lmax'-option via lmax=kmax rcom(z_mod)/(1+z_mod)
  #           with z_mod corresponding to a peak of the shear and photo-GC kernels 
  scale_cuts:
    type: 'const_lmax'
    max_WL: [2000]
            #[1., 1., 1., 1., 1.]
            #[1000, 
            #1000, 2000, 
            #1000, 2000, 2000,
            #1000, 2000, 2000, 3000,
            #2000, 2000, 2000, 3000, 3000] #always a list, same length as nbin*(nbin+1)/2 or just 1 for const_lmax
    max_GC: [900]
            #[0.4, 0.4, 0.4, 0.4, 0.4]
            #[500, 
            #400, 500, 
            #400, 600, 600,
            #400, 800, 800, 800,
            #400, 900, 900, 900, 900]
    cosmo: #or transformation from k_eff to ell
      'Omega_m': 0.31
      'w0': -1.
      'wa': 0.

  #Survey info
  #     Euclid: Euclid_5bins or Euclid_10bins
  #     LSST: LSST_Y1 or LSST_Y10 
  #     Custom: analytical n(z) or from file
  survey_info: 'LSST_Y1' #'Euclid_5bins'
  custom_survey_path: './custom_survey.yaml'


data:
  nl_model: 1
  #Nonlinear power spectrum
  #     0 -> HMcode
  #     1 -> bacco
  #----- not implemented yet:
  #     2 -> nDGP
  #     3 -> gLEMURS
  #     4 -> μ-Σ 
  #     5 -> Dark Scattering (Interacting Dark Energy)
  bias_model: 2
  # Photometric galaxy bias model (redshift dependence)
  #     0 -> constant linear bias within bins
  #     1 -> (b1, b2) constant within bins
  #     2 -> heft
  ia_model: 0
  # Intrinsic alignment model
  #     0 -> zNLA
  #----- not implemented yet:
  #     1 -> TATT
  baryon_model: 3
  # Baryonic flag
  #     0 -> no baryons
  #     1 -> Tagn HMcode
  #     2 -> bcemu
  #     3 -> bacco
  params: ./params_data.yaml

theory:
  nl_model: 1
  #Nonlinear power spectrum
  #     0 -> HMcode
  #     1 -> bacco
  #----- not implemented yet:
  #     2 -> nDGP
  #     3 -> gLEMURS
  #     4 -> μ-Σ 
  #     5 -> Dark Scattering (Interacting Dark Energy)
  bias_model: 2
  # Photometric galaxy bias model (redshift dependence)
  #     0 -> linear interpolation
  #     1 -> constant within bins
  #     2 -> heft
  ia_model: 0
  # Intrinsic alignment model
  #     0 -> zNLA
  #----- not implemented yet:
  #     1 -> TATT
  baryon_model: 3
  # Baryonic flag
  #     0 -> no baryons
  #     1 -> Tagn HMcode
  #     2 -> bcemu
  #     3 -> bacco
  params: ./params_bacco_test.yaml

output: 
  chain_name: params_debug
sampler: 
  mcmc:
    verbose: True
    n_eff: 10000
    n_live: 1000
    pool: 20
    resume: False
    hdf5_name: 'params_debug'
  #----- not implemented yet:  
  minimiser:
    verbose: True
    tolerance: 0.1
    
