################################################
#               COSMOLOGY                      #
################################################
Omega_m:
  type: 'U'
  p0: 0.31
  p1: 0.15
  p2: 0.6

Ombh2:
  type: 'G'
  p0: 0.02268
  p1: 0.02268
  p2: 0.00038

h:
  type: 'U'
  p0: 0.68
  p1: 0.5
  p2: 0.9

log10As:
  type: 'U'
  p0: 3.044
  p1: 1.7
  p2: 4.

ns:
  type: 'G'
  p0: 0.97
  p1: 0.97
  p2: 0.004    

Mnu: 
  type: 'F'
  p0: 0.0
w0: 
  type: 'F'
  p0: -1.
wa: 
  type: 'F'
  p0: 0.0    


################################################
#               Nuisances                      #
################################################
aIA:
  type: 'U'
  p0: 1.72
  p1: 0.
  p2: 12.1

etaIA:
  type: 'U'
  p0: -0.41 
  p1: -7.
  p2: 6.17    

b1_1:
  type: 'U'
  p0: 0.68
  p1: 0.
  p2: 4.        
b1_2:
  type: 'U'
  p0: 0.68
  p1: 0.
  p2: 4.   
b1_3:
  type: 'U'
  p0: 0.68
  p1: 0.
  p2: 4.   
b1_4:
  type: 'U'
  p0: 0.68
  p1: 0.
  p2: 4.               
b1_5:
  type: 'U'
  p0: 0.68
  p1: 0.
  p2: 4.     